engines:
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
    checks:
      PhanUndeclaredVariable:  # TMP turned off for $this
        enabled: false
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php

ratings:
  paths:
  - "**.php"
  - "**.js"
  - "**.css"

exclude_paths:
  - "vendor/*"
