# render.yaml

services:
  # The Laravel Web Service
  - type: web
    name: ote-web
    plan: free
    # All build and start commands are now in the Dockerfile
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ote-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ote-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ote-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ote-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ote-db
          property: password

# The PostgreSQL Database is defined in its own top-level list
databases:
  - name: ote-db
    plan: free
